# Generated by Django 6.0.7 on 2026-07-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Aakash Auto Hub', max_length=160)),
                ('tagline', models.CharField(blank=True, default='Bus & Car AC Parts Specialist', max_length=220)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business/')),
                ('about_text', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('whatsapp_message_template', models.TextField(default="Hi, I'm interested in {product_name} (Part No: {part_number}). Please share more details.")),
                ('address', models.TextField(blank=True)),
                ('map_embed_link', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Business Info',
                'verbose_name_plural': 'Business Info',
            },
        ),
        migrations.CreateModel(
            name='EnquiryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Call')], max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_logs', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Enquiry Log',
                'verbose_name_plural': 'Enquiry Logs',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['clicked_at'], name='core_enquir_clicked_42ab4e_idx'), models.Index(fields=['source'], name='core_enquir_source_eb35ea_idx')],
            },
        ),
    ]
