# Generated by Django 6.0.7 on 2026-07-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
