# Generated by Django 6.0.7 on 2026-08-01 15:01

from django.db import migrations, models


def select_existing_homepage_categories(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    categories = Category.objects.filter(is_active=True).order_by('display_order', 'name')[:8]
    for position, category in enumerate(categories, start=1):
        category.show_on_homepage = True
        category.homepage_order = position
        category.save(update_fields=['show_on_homepage', 'homepage_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='homepage_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'show_on_homepage', 'homepage_order'], name='catalog_cat_is_acti_e4f69c_idx'),
        ),
        migrations.RunPython(select_existing_homepage_categories, migrations.RunPython.noop),
    ]
